name: Aqua Trivy Orchestration Security Scan

on:
  workflow_dispatch:
    inputs:
      harness-org-id:
        description: 'Harness Organization ID'
        required: true
        type: string
      harness-project-id:
        description: 'Harness Project ID'
        required: true
        type: string
      harness-domain:
        description: 'Harness domain (e.g., https://app.harness.io)'
        required: false
        type: string
        default: 'https://app.harness.io'

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run Harness STO Scan
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: aqua_trivy
          scan-mode: orchestration
          image-name: "nginx:latest"  
          image-tag: "latest"
          scan-config: fs
          target-type: repository


          workspace: .

          fail-on-severity: HIGH
          show-summary: true