name: Semgrep Orchestration Security Scan

on:
  workflow_dispatch:
    inputs:
      harness-org-id:
        description: 'Harness Organization ID'
        required: true
        type: string
      harness-project-id:
        description: 'Harness Project ID'
        required: true
        type: string
      harness-domain:
        description: 'Harness domain (e.g., https://app.harness.io)'
        required: false
        type: string
        default: 'https://app.harness.io'

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Run Semgrep scan-third-party-dependencies scan with default target
        id: sto-scan-third-party-default
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: scan-third-party-dependencies
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          output-file: scan-output-third-party-default.env
          show-summary: 'true'

      - name: Run Semgrep scan-third-party-dependencies scan with named target
        id: sto-scan-third-party
        if: always()
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: scan-third-party-dependencies
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          target-name: "shreyansh/semgrepthirdparty"
          target-variant: "main"
          output-file: scan-output-third-party.env
          show-summary: 'true'

      - name: Run Semgrep auto-and-ported-security-tools-except-p-gitleaks scan with default target
        id: sto-scan-auto-ported-except-gitleaks-default
        if: always()
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: auto-and-ported-security-tools-except-p-gitleaks
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          output-file: scan-output-auto-ported-except-gitleaks-default.env
          show-summary: 'true'

      - name: Run Semgrep auto-and-ported-security-tools-except-p-gitleaks scan with named target
        id: sto-scan-auto-ported-except-gitleaks
        if: always()
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: auto-and-ported-security-tools-except-p-gitleaks
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          target-name: "shreyansh/semgrepautoportedexceptgitleaks"
          target-variant: "main"
          output-file: scan-output-auto-ported-except-gitleaks.env
          show-summary: 'true'

      - name: Run Semgrep auto-and-ported-security-tools scan with default target
        id: sto-scan-auto-ported-default
        if: always()
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: auto-and-ported-security-tools
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          output-file: scan-output-auto-ported-default.env
          show-summary: 'true'

      - name: Run Semgrep auto-and-ported-security-tools scan with named target
        id: sto-scan-auto-ported
        if: always()
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: auto-and-ported-security-tools
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          target-name: "shreyansh/semgrepautoported"
          target-variant: "main"
          output-file: scan-output-auto-ported.env
          show-summary: 'true'

      - name: Run Semgrep auto-only scan with default target
        id: sto-scan-auto-only-default
        if: always()
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: auto-only
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          output-file: scan-output-auto-only-default.env
          show-summary: 'true'

      - name: Run Semgrep auto-only scan with named target
        id: sto-scan-auto-only
        if: always()
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: auto-only
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          target-name: "shreyansh/semgrepautoonly"
          target-variant: "main"
          output-file: scan-output-auto-only.env
          show-summary: 'true'

      - name: Run Semgrep p-default scan with default target
        id: sto-scan-p-default-default
        if: always()
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: p-default
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          output-file: scan-output-p-default-default.env
          show-summary: 'true'

      - name: Run Semgrep p-default scan with named target
        id: sto-scan-p-default
        if: always()
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: p-default
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          target-name: "shreyansh/semgreppdefault"
          target-variant: "main"
          output-file: scan-output-p-default.env
          show-summary: 'true'

      - name: Run Semgrep no-default-cli-flags scan with default target
        id: sto-scan-no-default-cli-flags-default
        if: always()
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: no-default-cli-flags
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          output-file: scan-output-no-default-cli-flags-default.env
          show-summary: 'true'

      - name: Run Semgrep no-default-cli-flags scan with named target
        id: sto-scan-no-default-cli-flags
        if: always()
        uses: ./.github/actions/harness-sto
        with:
          harness-token: ${{ secrets.HARNESS_TOKEN }}
          harness-org-id: ${{ inputs.harness-org-id }}
          harness-project-id: ${{ inputs.harness-project-id }}
          harness-domain: ${{ inputs.harness-domain }}

          scanner: semgrep
          scan-mode: orchestration
          scan-config: no-default-cli-flags
          target-type: repository
          workspace: .
          docker-image-tag: "dev"
          target-name: "shreyansh/semgrepnodefaultcliflags"
          target-variant: "main"
          output-file: scan-output-no-default-cli-flags.env
          show-summary: 'true'
      - name: Use scan output variables
        if: always()
        shell: bash
        run: |
          echo "===== STO Scan Output Variables (scan-third-party-dependencies default target) ====="
          echo "Scan ID: ${{ steps.sto-scan-third-party-default.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-third-party-default.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-third-party-default.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-third-party-default.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-third-party-default.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-third-party-default.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-third-party-default.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-third-party-default.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-third-party-default.outputs.output-file-path }}"

          echo "===== STO Scan Output Variables (scan-third-party-dependencies) ====="
          echo "Scan ID: ${{ steps.sto-scan-third-party.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-third-party.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-third-party.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-third-party.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-third-party.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-third-party.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-third-party.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-third-party.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-third-party.outputs.output-file-path }}"

          echo "===== STO Scan Output Variables (auto-and-ported-security-tools-except-p-gitleaks default target) ====="
          echo "Scan ID: ${{ steps.sto-scan-auto-ported-except-gitleaks-default.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-auto-ported-except-gitleaks-default.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-auto-ported-except-gitleaks-default.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-auto-ported-except-gitleaks-default.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-auto-ported-except-gitleaks-default.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-auto-ported-except-gitleaks-default.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-auto-ported-except-gitleaks-default.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-auto-ported-except-gitleaks-default.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-auto-ported-except-gitleaks-default.outputs.output-file-path }}"

          echo "===== STO Scan Output Variables (auto-and-ported-security-tools-except-p-gitleaks) ====="
          echo "Scan ID: ${{ steps.sto-scan-auto-ported-except-gitleaks.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-auto-ported-except-gitleaks.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-auto-ported-except-gitleaks.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-auto-ported-except-gitleaks.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-auto-ported-except-gitleaks.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-auto-ported-except-gitleaks.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-auto-ported-except-gitleaks.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-auto-ported-except-gitleaks.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-auto-ported-except-gitleaks.outputs.output-file-path }}"

          echo "===== STO Scan Output Variables (auto-and-ported-security-tools default target) ====="
          echo "Scan ID: ${{ steps.sto-scan-auto-ported-default.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-auto-ported-default.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-auto-ported-default.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-auto-ported-default.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-auto-ported-default.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-auto-ported-default.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-auto-ported-default.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-auto-ported-default.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-auto-ported-default.outputs.output-file-path }}"

          echo "===== STO Scan Output Variables (auto-and-ported-security-tools) ====="
          echo "Scan ID: ${{ steps.sto-scan-auto-ported.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-auto-ported.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-auto-ported.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-auto-ported.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-auto-ported.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-auto-ported.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-auto-ported.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-auto-ported.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-auto-ported.outputs.output-file-path }}"

          echo "===== STO Scan Output Variables (auto-only default target) ====="
          echo "Scan ID: ${{ steps.sto-scan-auto-only-default.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-auto-only-default.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-auto-only-default.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-auto-only-default.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-auto-only-default.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-auto-only-default.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-auto-only-default.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-auto-only-default.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-auto-only-default.outputs.output-file-path }}"

          echo "===== STO Scan Output Variables (auto-only) ====="
          echo "Scan ID: ${{ steps.sto-scan-auto-only.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-auto-only.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-auto-only.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-auto-only.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-auto-only.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-auto-only.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-auto-only.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-auto-only.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-auto-only.outputs.output-file-path }}"

          echo "===== STO Scan Output Variables (p-default default target) ====="
          echo "Scan ID: ${{ steps.sto-scan-p-default-default.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-p-default-default.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-p-default-default.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-p-default-default.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-p-default-default.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-p-default-default.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-p-default-default.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-p-default-default.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-p-default-default.outputs.output-file-path }}"

          echo "===== STO Scan Output Variables (p-default) ====="
          echo "Scan ID: ${{ steps.sto-scan-p-default.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-p-default.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-p-default.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-p-default.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-p-default.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-p-default.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-p-default.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-p-default.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-p-default.outputs.output-file-path }}"

          echo "===== STO Scan Output Variables (no-default-cli-flags default target) ====="
          echo "Scan ID: ${{ steps.sto-scan-no-default-cli-flags-default.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-no-default-cli-flags-default.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-no-default-cli-flags-default.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-no-default-cli-flags-default.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-no-default-cli-flags-default.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-no-default-cli-flags-default.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-no-default-cli-flags-default.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-no-default-cli-flags-default.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-no-default-cli-flags-default.outputs.output-file-path }}"

          echo "===== STO Scan Output Variables (no-default-cli-flags) ====="
          echo "Scan ID: ${{ steps.sto-scan-no-default-cli-flags.outputs.scan-id }}"
          echo "Status: ${{ steps.sto-scan-no-default-cli-flags.outputs.status }}"
          echo "Total Issues: ${{ steps.sto-scan-no-default-cli-flags.outputs.total-issues }}"
          echo "Critical: ${{ steps.sto-scan-no-default-cli-flags.outputs.critical }}"
          echo "High: ${{ steps.sto-scan-no-default-cli-flags.outputs.high }}"
          echo "Medium: ${{ steps.sto-scan-no-default-cli-flags.outputs.medium }}"
          echo "Low: ${{ steps.sto-scan-no-default-cli-flags.outputs.low }}"
          echo "Info: ${{ steps.sto-scan-no-default-cli-flags.outputs.info }}"
          echo "Output File Path: ${{ steps.sto-scan-no-default-cli-flags.outputs.output-file-path }}"

      - name: Archive scan output (scan-third-party-dependencies default target)
        if: always() && steps.sto-scan-third-party-default.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-third-party-default
          path: ${{ steps.sto-scan-third-party-default.outputs.output-file-path }}
          retention-days: 1

      - name: Archive scan output (scan-third-party-dependencies)
        if: always() && steps.sto-scan-third-party.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-third-party
          path: ${{ steps.sto-scan-third-party.outputs.output-file-path }}
          retention-days: 1

      - name: Archive scan output (auto-and-ported-security-tools-except-p-gitleaks default target)
        if: always() && steps.sto-scan-auto-ported-except-gitleaks-default.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-auto-ported-except-gitleaks-default
          path: ${{ steps.sto-scan-auto-ported-except-gitleaks-default.outputs.output-file-path }}
          retention-days: 1

      - name: Archive scan output (auto-and-ported-security-tools-except-p-gitleaks)
        if: always() && steps.sto-scan-auto-ported-except-gitleaks.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-auto-ported-except-gitleaks
          path: ${{ steps.sto-scan-auto-ported-except-gitleaks.outputs.output-file-path }}
          retention-days: 1

      - name: Archive scan output (auto-and-ported-security-tools default target)
        if: always() && steps.sto-scan-auto-ported-default.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-auto-ported-default
          path: ${{ steps.sto-scan-auto-ported-default.outputs.output-file-path }}
          retention-days: 1

      - name: Archive scan output (auto-and-ported-security-tools)
        if: always() && steps.sto-scan-auto-ported.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-auto-ported
          path: ${{ steps.sto-scan-auto-ported.outputs.output-file-path }}
          retention-days: 1

      - name: Archive scan output (auto-only default target)
        if: always() && steps.sto-scan-auto-only-default.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-auto-only-default
          path: ${{ steps.sto-scan-auto-only-default.outputs.output-file-path }}
          retention-days: 1

      - name: Archive scan output (auto-only)
        if: always() && steps.sto-scan-auto-only.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-auto-only
          path: ${{ steps.sto-scan-auto-only.outputs.output-file-path }}
          retention-days: 1

      - name: Archive scan output (p-default default target)
        if: always() && steps.sto-scan-p-default-default.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-p-default-default
          path: ${{ steps.sto-scan-p-default-default.outputs.output-file-path }}
          retention-days: 1

      - name: Archive scan output (p-default)
        if: always() && steps.sto-scan-p-default.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-p-default
          path: ${{ steps.sto-scan-p-default.outputs.output-file-path }}
          retention-days: 1

      - name: Archive scan output (no-default-cli-flags default target)
        if: always() && steps.sto-scan-no-default-cli-flags-default.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-no-default-cli-flags-default
          path: ${{ steps.sto-scan-no-default-cli-flags-default.outputs.output-file-path }}
          retention-days: 1

      - name: Archive scan output (no-default-cli-flags)
        if: always() && steps.sto-scan-no-default-cli-flags.outputs.output-file-path != ''
        uses: actions/upload-artifact@v4
        with:
          name: sto-scan-results-no-default-cli-flags
          path: ${{ steps.sto-scan-no-default-cli-flags.outputs.output-file-path }}
          retention-days: 1
